# Stage 1: Build the Node.js environment
FROM node:18.13.0 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --only=dev

# Install necessary dependencies for Chromium
RUN apt-get update && apt-get install -y \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY ./backend-services ./backend-services
COPY ./data ./data

CMD ["node", "./backend-services/start-scraper.js"]
