# Stage 1: Build the Node.js environment
FROM node:18.13.0 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --only=dev

RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'

RUN apt-get update && apt-get install -y \
    google-chrome-stable \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY ./backend-services ./backend-services
COPY ./data ./data

CMD ["node", "./backend-services/start-scraper.js"]
